#!/bin/sh
#
# Called by git-commit with no arguments.  This checks to make
# sure that all .c and .h files are indented correctly before
# a commit is made.
#
# To enable this hook, make this file executable and place it
# in $GIT_DIR/hooks.

. git-sh-setup

CHFILES=$(git diff --name-only --diff-filter=AM HEAD | grep '.*\.[ch]$')

for CHFILE in $CHFILES;
do
  MKTEMPLATE=$(basename "$CHFILE").XXXXXXXX
  TEMPFILE=$(mktemp -t "$MKTEMPLATE") || exit 1
  TEMPFILE_FORMATED=$(mktemp -t "$MKTEMPLATE") || exit 1
  git show :"$CHFILE" > "$TEMPFILE"
  clang-format "$TEMPFILE" > "$TEMPFILE_FORMATED"
  if diff "$TEMPFILE" "$TEMPFILE_FORMATED"
  then
    rm -f "$TEMPFILE" "$TEMPFILE_FORMATED"
  else
    rm -f "$TEMPFILE" "$TEMPFILE_FORMATED"
    NEEDS_FORMAT=1
    echo >&2 "$CHFILE needs to be indented with:"
    echo >&2 "   clang-format -i \"$GIT_DIR/../$CHFILE\""
  fi
done
if [ -z "$NEEDS_FORMAT" ]
then
  exit 0
else
  exit 1
fi
